In [2]:
import pandas as pd
from sklearn.datasets import load_iris
iris=load_iris()

In [5]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
df['target'] = iris.target

In [8]:
X = df.drop('target',axis='columns')
y = df.target

In [ ]:
df['target'] = iris.target
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [9]:
X = df.drop('target',axis='columns')
y = df.target

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [11]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=10)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10)

In [12]:
model.predict(X_test)

array([2, 0, 0, 1, 2, 2, 2, 2, 1, 0, 1, 1, 0, 2, 0, 2, 1, 2, 0, 0, 1, 1,
       1, 0, 0, 2, 2, 1, 0, 0])

In [13]:
model.score(X_test, y_test)

1.0

In [14]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=30)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=30)

In [15]:
model.predict(X_test)

array([2, 0, 0, 1, 2, 2, 2, 2, 1, 0, 1, 1, 0, 2, 0, 2, 1, 2, 0, 0, 1, 1,
       1, 0, 0, 2, 2, 1, 0, 0])

In [16]:
model.score(X_test, y_test)

1.0

In [17]:
best_score = 0
best_n = 0

for n in range(1, 101):
    model = RandomForestClassifier(n_estimators=n, random_state=42)
    model.fit(X_train, y_train)
    score = model.score(X_test, y_test)

    if score > best_score:
        best_score = score
        best_n = n

print("Best number of trees:", best_n)
print("Best accuracy:", best_score)

Best number of trees: 1
Best accuracy: 1.0